buildscript {
    ext {
        compose_ui_version = '1.6.0' // فصلنا إصدار الـ UI
        compose_compiler_version = '1.5.3' // إصدار الـ Compiler
    }
}
plugins {
    id 'com.android.application' version '8.1.1' apply false // تم ترقية Gradle Plugin
    id 'com.android.library' version '8.1.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.0' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
