workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      vars:
        GRADLE_WRAPPER_VERSION: "8.0" 
    scripts:
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/**.apk
