pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    // قمت بتغيير هذا السطر ليمنع فشل البناء إذا تعذر الوصول لمستودع مؤقتاً
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "Fiend"
include ':app'
