pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS) // تم التغيير هنا
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "Fiend"
include ':app'
